export enum PermissionBaseEnum {
  ADD = '::ADD',
  MODIFY = '::MODIFY',
  DELETE = '::DELETE',
  QUERY_PAGED = '::QUERY::PAGED',
  QUERY_LIST = '::QUERY::LIST',
  QUERY_ID = '::QUERY::ID',
  USER_UPDATE_ENABLED = '::USER::UPDATE::ENABLED',
  USER_GRANTED_ROLE = '::USER::GRANTED::ROLE',
  USER_RESET_PASSWORD = '::USER::RESET::PASSWORD',
  GRANT_PAGE_PERMISSION = '::GRANT::PAGE::PERMISSION',
  ROLE_GRANT = '::ROLE::GRANT'
}
